name: chat
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - playwright
    - python-dotenv
    - python-telegram-bot==20.0a6
    - requests
    - google-search-results
    - stability-sdk
    - pillow~=9.3.0
    - ffmpeg==4.2.2
    - SpeechRecognition==3.9.0
